version: '3.8'

services:
  harbor:
    image: goharbor/harbor-all:v2.12.0
    container_name: harbor
    restart: always
    volumes:
      - harbor_data:/data
      - ./harbor.yml:/etc/harbor/harbor.yml
    ports:
      - "8080:80"
    environment:
      - HARBOR_ADMIN_PASSWORD=admin123
    networks:
      - bridge

volumes:
  harbor_data:

networks:
  bridge:
    external: true
